/**
 * @fileoverview This file contains the data generation logic for the Ollama response.
 */

/**
 * Defines the structure of the data object returned by the generator.
 */
export interface OllamaData {
  message: string; // A general message
  timestamp: Date;
  model: string;
  entriesByDate: { [date: string]: string[] }; // New property: date -> entries
}

/**
 * Generates the data object. In a real-world scenario, this function
 * would contain the logic to call the Ollama model and format the response.
 * @returns {OllamaData} The generated data object.
 */
export function generateJsonData(): OllamaData {
  // For now, we'll return a static object.
  // In a real application, this is where you'd fetch data from Ollama.

  const entriesByDate: { [date: string]: string[] } = {
    "2025-11-19": ["Entry 1 for 2025-11-19", "Entry 2 for 2025-11-19"],
    "2025-11-20": ["Entry 1 for 2025-11-20"],
  };

  return {
    message: "This JSON was generated by a dedicated function!",
    timestamp: new Date(),
    model: "llama2",
    entriesByDate: entriesByDate,
  };
}