/**
 * @fileoverview This file contains the data generation logic for the Ollama response.
 */
/**
 * Represents a single training activity with a date, description, and discipline.
 */
export  abstract class TrainingActivity {
  date: Date;
  description: string;
  discipline: string;
  done: boolean = false;

  constructor(date: Date, description: string, discipline: string) {
    this.date = date;
    this.description = description;
    this.discipline = discipline;
  }
}

/**
 * Represents a running activity, inheriting from TrainingActivity.
 * It automatically sets the discipline to "Running" and adds a distance property.
 */
export class Running extends TrainingActivity {
  constructor(
    public date: Date,
    public description: string,
    public distance: number // Additional field for Running
  ) {
    // Call the parent constructor with a fixed discipline
    super(date, description, "Running");
  }
}
export class Cycling extends TrainingActivity {
  constructor(
    public date: Date,
    public description: string,
    public distance: number // Additional field for Running
  ) {
    // Call the parent constructor with a fixed discipline
    super(date, description, "Cycling");
  }
}
export class Swimming extends TrainingActivity {
  constructor(
    public date: Date,
    public description: string,
    public distance: number // Additional field for Running
  ) {
    // Call the parent constructor with a fixed discipline
    super(date, description, "Swimming");
  }
}

export class TrainingPlan {
  activities: TrainingActivity[] = [];

  addActivity(activity: TrainingActivity) {
    this.activities.push(activity);
    this.activities.sort((a, b) => a.date.getTime() - b.date.getTime());
  }

  getEntriesByDate(): { [date: string]: string[] } {
    const entries: { [date: string]: string[] } = {};
    for (const activity of this.activities) {
      const dateKey = activity.date.toISOString().split("T")[0]; // Format date as 'YYYY-MM-DD'
      if (!entries[dateKey]) {
        entries[dateKey] = [];
      }
      entries[dateKey].push(activity.description);
    }
    return entries;
  }
}

export interface OllamaData {
  message: string; // A general message
  timestamp: Date;
  model: string;
  entriesByDate: { [date: string]: string[] }; // New property: date -> entries
}

export function generateJsonData(): OllamaData {
  // For now, we'll return a static object.
  // In a real application, this is where you'd fetch data from Ollama.
  const plan = new TrainingPlan();

  // Add some sample activities to the plan
  plan.addActivity(new Running(new Date("2025-11-19"), "Morning Run", 5)); // Use the new Running class
  plan.addActivity(new Cycling(new Date("2025-11-22"), "Morning Cycle", 5)); // Use the new Running class
  plan.addActivity(new Swimming(new Date("2025-11-31"), "Morning Swim", 5)); // Use the new Running class
  return {
    message: "This JSON was generated by a dedicated function!",
    timestamp: new Date(),
    model: "llama2",
    entriesByDate: plan.getEntriesByDate(),
  };
}
