/**
 * @fileoverview This file contains the data generation logic for the Ollama response.
 */

import { TrainingActivity, Running, Cycling, Swimming } from './training-activity';

export class TrainingPlan {
  activities: TrainingActivity[] = [];

  addActivity(activity: TrainingActivity) {
    this.activities.push(activity);
    this.activities.sort((a, b) => a.date.getTime() - b.date.getTime());
  }

  getEntriesByDate(): { [date: string]: { description: string; discipline: string; done: boolean; plannedDuration: number }[] } {
    const entries: { [date: string]: { description: string; discipline: string; done: boolean; plannedDuration: number }[] } = {};
    for (const activity of this.activities) {
      const dateKey = activity.date.toISOString().split("T")[0]; // Format date as 'YYYY-MM-DD'
      if (!entries[dateKey]) {
        entries[dateKey] = [];
      }
      // Push a detailed object instead of just the description string
      entries[dateKey].push({
        description: activity.description,
        discipline: activity.discipline,
        done: activity.isDone(),
        plannedDuration: activity.plannedDuration, // Add plannedDuration here
      });
    }
    return entries;
  }
}

export interface OllamaData {
  message: string; // A general message
  timestamp: Date;
  model: string;
  entriesByDate: { [date: string]: { description: string; discipline: string; done: boolean; plannedDuration: number }[] };
}

export function generateJsonData(): OllamaData {
  // For now, we'll return a static object.
  // In a real application, this is where you'd fetch data from Ollama.
  const plan = new TrainingPlan();

  // Add some sample activities to the plan
  const runningActivity = new Running(new Date("2025-11-19"), "Morning Run", 30, 5); // 30 minutes, 5km
  runningActivity.markAsDone(); // Mark this one as done for demonstration
  plan.addActivity(runningActivity);

  plan.addActivity(new Cycling(new Date("2025-11-22"), "Morning Cycle", 60, 25)); // 60 minutes, 25km
  plan.addActivity(new Swimming(new Date("2025-11-31"), "Morning Swim", 45, 1.5)); // 45 minutes, 1.5km
  return {
    message: "This JSON was generated by a dedicated function!",
    timestamp: new Date(),
    model: "llama2",
    entriesByDate: plan.getEntriesByDate(),
  };
}
