/**
 * @fileoverview This file contains the data generation logic for the Ollama response.
 */
import { Interval } from './interval';
import { Running, Cycling, Swimming } from './training-activity';
import { TrainingPlan } from './training-plan';

export interface OllamaData {
  message: string; // A general message
  timestamp: Date;
  model: string;
  entriesByDate: { [date: string]: { description: string; discipline: string; done: boolean; plannedDuration: number }[] };
}

export function generateJsonData(): OllamaData {
  // For now, we'll return a static object.
  // In a real application, this is where you'd fetch data from Ollama.
  const plan = new TrainingPlan();

  // Add some sample activities to the plan
  const runningActivity = new Running(new Date("2025-11-19"), "Morning Run", 30, 5); // 30 minutes, 5km
  runningActivity.markAsDone(); // Mark this one as done for demonstration
  plan.addActivity(runningActivity);
  let a1 = new Cycling(new Date("2025-11-22"), "Morning Cycle", 60, 25)
  let int1= new Interval('faast',15, 'high', 5);
  let int2= new Interval('slow',15, 'low', 15);
  a1.addInterval(int1);
  a1.addInterval(int2);
  plan.addActivity(a1); // 60 minutes, 25km
  plan.addActivity(new Swimming(new Date("2025-11-31"), "Morning Swim", 45, 1.5)); // 45 minutes, 1.5km
  return {
    message: "This JSON was generated by a dedicated function!",
    timestamp: new Date(),
    model: "llama2",
    entriesByDate: plan.getEntriesByDate(),
  };
}
